apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval:
    rule_files:
      - "first_rules.yml"
    srape_configs:
      - job_name:'prometheus'
    static_configs:
      - targets:['localhost:9090','192.168.0.9:9090']